### PR TITLE
Unskip Windows build

### LINKED ISSUE #18: Windows builds missing
Would be nice to have though

### PR DESCRIPTION
**Pull request by dagewa**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

closes #18

### CODE REVIEW

**Comment by dagewa** [comment]
@conda-forge-admin, please rerender

**Comment by dagewa** [comment]
@xmnlab I had a quick look through the files under `info/recipe` in the PSI bitshuffle package, but I could not easily tell what, if anything, might need changing here. However, I note:

* it takes [specific revision](https://github.com/kiyo-masui/bitshuffle/commit/cc6c11216b88863f5c1958ebfd99175eea82bac7) as source rather than a tarball
* `meta.yaml.template` contains as a build requirement `{{ compiler('cxx') }}` rather than `{{ compiler('c') }}` (maybe this is not different on Windows anyway)
* it patches to ensure `OMP_DEFAULT = False` on all platforms

**Comment by dagewa** [comment]
well, this looks fairly unhappy, though I'm not sure what the problems are.

**Comment by Anthchirp** [comment]
Tests are failing because an older version of h5py is assumed, relevant patch is https://github.com/kiyo-masui/bitshuffle/commit/35a18aef4a6bc982c6685c21ab41c3c8823eea98.patch

**Comment by Anthchirp** [comment]
Linux/MacOS tests are now passing again.

Windows build is failing [because there is no build script](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=295594&view=logs&j=00f5923e-fdef-5026-5091-0d5a0b3d5a2c&t=3cc4a9ed-60e1-5810-6eb3-5f9cd4a26dba&l=143)

You'll need to add a `build.bat` that runs the Windows equivalent to [`build.sh`](https://github.com/conda-forge/bitshuffle-feedstock/blob/master/recipe/build.sh)

**Comment by xmnlab** [comment]
> it takes specific revision as source rather than a tarball

@dagewa not sure if it can be a big difference, maybe it can. the latest stable version is very old. I ask about that in the bitshuffle repository, but I still waiting for a response https://github.com/kiyo-masui/bitshuffle/issues/94

**Comment by dagewa** [comment]
I've been trying to build locally but there are test failures so the build fails. Pushed this anyway as a starting point

**Comment by Anthchirp** [comment]
@conda-forge-admin, please rerender

**Comment by Anthchirp** [comment]
```
building 'bitshuffle.h5' extension
"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -DBSHUF_VERSION_MAJOR=0 -DBSHUF_VERSION_MINOR=4 -DBSHUF_VERSION_POINT=1 -DH5_USE_18_API -Isrc/ -Ilz4/ -I%PREFIX%\include -I%PREFIX%\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\cppwinrt" -I%PREFIX%\Library\include -I%PREFIX%\Library\include /d1trimfile:%SRC_DIR% /Tcbitshuffle/h5.c /Fobuild\temp.win-amd64-3.8\Release\bitshuffle/h5.obj -DH5_BUILT_AS_DYNAMIC_LIB /Ox /fp:fast /openmp
h5.c
"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -DBSHUF_VERSION_MAJOR=0 -DBSHUF_VERSION_MINOR=4 -DBSHUF_VERSION_POINT=1 -DH5_USE_18_API -Isrc/ -Ilz4/ -I%PREFIX%\include -I%PREFIX%\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\cppwinrt" -I%PREFIX%\Library\include -I%PREFIX%\Library\include /d1trimfile:%SRC_DIR% /Tclz4/lz4.c /Fobuild\temp.win-amd64-3.8\Release\lz4/lz4.obj -DH5_BUILT_AS_DYNAMIC_LIB /Ox /fp:fast /openmp
lz4.c
"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -DBSHUF_VERSION_MAJOR=0 -DBSHUF_VERSION_MINOR=4 -DBSHUF_VERSION_POINT=1 -DH5_USE_18_API -Isrc/ -Ilz4/ -I%PREFIX%\include -I%PREFIX%\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\cppwinrt" -I%PREFIX%\Library\include -I%PREFIX%\Library\include /d1trimfile:%SRC_DIR% /Tcsrc/bitshuffle.c /Fobuild\temp.win-amd64-3.8\Release\src/bitshuffle.obj -DH5_BUILT_AS_DYNAMIC_LIB /Ox /fp:fast /openmp
bitshuffle.c
src/bitshuffle.c(44): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
src/bitshuffle.c(61): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
src/bitshuffle.c(68): warning C4244: 'function': conversion from 'int64_t' to 'uint32_t', possible loss of data
src/bitshuffle.c(100): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
src/bitshuffle.c(221): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
src/bitshuffle.c(224): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -DBSHUF_VERSION_MAJOR=0 -DBSHUF_VERSION_MINOR=4 -DBSHUF_VERSION_POINT=1 -DH5_USE_18_API -Isrc/ -Ilz4/ -I%PREFIX%\include -I%PREFIX%\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\cppwinrt" -I%PREFIX%\Library\include -I%PREFIX%\Library\include /d1trimfile:%SRC_DIR% /Tcsrc/bitshuffle_core.c /Fobuild\temp.win-amd64-3.8\Release\src/bitshuffle_core.obj -DH5_BUILT_AS_DYNAMIC_LIB /Ox /fp:fast /openmp
bitshuffle_core.c
src/bitshuffle_core.c(198): warning C4146: unary minus operator applied to unsigned type, result still unsigned
src/bitshuffle_core.c(212): warning C4244: '=': conversion from 'uint64_t' to 'uint8_t', possible loss of data
src/bitshuffle_core.c(321): warning C4146: unary minus operator applied to unsigned type, result still unsigned
src/bitshuffle_core.c(341): warning C4244: '=': conversion from 'uint64_t' to 'uint8_t', possible loss of data
src/bitshuffle_core.c(1780): warning C4244: '=': conversion from 'uint64_t' to 'uint8_t', possible loss of data
"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -DBSHUF_VERSION_MAJOR=0 -DBSHUF_VERSION_MINOR=4 -DBSHUF_VERSION_POINT=1 -DH5_USE_18_API -Isrc/ -Ilz4/ -I%PREFIX%\include -I%PREFIX%\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\cppwinrt" -I%PREFIX%\Library\include -I%PREFIX%\Library\include /d1trimfile:%SRC_DIR% /Tcsrc/bshuf_h5filter.c /Fobuild\temp.win-amd64-3.8\Release\src/bshuf_h5filter.obj -DH5_BUILT_AS_DYNAMIC_LIB /Ox /fp:fast /openmp
bshuf_h5filter.c
src/bshuf_h5filter.c(57): warning C4267: '=': conversion from 'size_t' to 'unsigned int', possible loss of data
src/bshuf_h5filter.c(69): warning C4996: 'sprintf': This function or variable may be unsafe. Consider using sprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
C:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt\stdio.h(1764): note: see declaration of 'sprintf'
src/bshuf_h5filter.c(183): warning C4244: '=': conversion from 'int64_t' to 'int', possible loss of data
src/bshuf_h5filter.c(199): warning C4267: 'function': conversion from 'size_t' to 'uint32_t', possible loss of data
src/bshuf_h5filter.c(202): warning C4244: '=': conversion from 'int64_t' to 'int', possible loss of data
src/bshuf_h5filter.c(216): warning C4244: '=': conversion from 'int64_t' to 'int', possible loss of data
src/bshuf_h5filter.c(219): warning C4244: '=': conversion from 'int64_t' to 'int', possible loss of data
src/bshuf_h5filter.c(224): warning C4996: 'sprintf': This function or variable may be unsafe. Consider using sprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
C:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt\stdio.h(1764): note: see declaration of 'sprintf'
"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -DBSHUF_VERSION_MAJOR=0 -DBSHUF_VERSION_MINOR=4 -DBSHUF_VERSION_POINT=1 -DH5_USE_18_API -Isrc/ -Ilz4/ -I%PREFIX%\include -I%PREFIX%\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\cppwinrt" -I%PREFIX%\Library\include -I%PREFIX%\Library\include /d1trimfile:%SRC_DIR% /Tcsrc/iochain.c /Fobuild\temp.win-amd64-3.8\Release\src/iochain.obj -DH5_BUILT_AS_DYNAMIC_LIB /Ox /fp:fast /openmp
iochain.c
"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\link.exe" /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:%PREFIX%\libs /LIBPATH:%PREFIX% /LIBPATH:%PREFIX%\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.16.27023\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.16.27023\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.22000.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.22000.0\um\x64" /LIBPATH:%PREFIX%\Library\lib /LIBPATH:%PREFIX%\Library\lib hdf5.lib /EXPORT:PyInit_h5 build\temp.win-amd64-3.8\Release\bitshuffle/h5.obj build\temp.win-amd64-3.8\Release\lz4/lz4.obj build\temp.win-amd64-3.8\Release\src/bitshuffle.obj build\temp.win-amd64-3.8\Release\src/bitshuffle_core.obj build\temp.win-amd64-3.8\Release\src/bshuf_h5filter.obj build\temp.win-amd64-3.8\Release\src/iochain.obj /OUT:build\lib.win-amd64-3.8\bitshuffle\h5.cp38-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.8\Release\bitshuffle\h5.cp38-win_amd64.lib /openmp
LINK : warning LNK4044: unrecognized option '/openmp'; ignored
   Creating library build\temp.win-amd64-3.8\Release\bitshuffle\h5.cp38-win_amd64.lib and object build\temp.win-amd64-3.8\Release\bitshuffle\h5.cp38-win_amd64.exp
h5.obj : error LNK2001: unresolved external symbol init_filter
```

**Comment by ndevenish** [comment]
We can't remember the need for this. We can revisit if we want windows again.

**Pull request closed without merging**
