### PR TITLE
Add python 3.8 builds

### PR DESCRIPTION
**Pull request by Anthchirp**
The first attempt was botched, so try this again (this time with help from CF core team)

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Anthchirp** [comment]
@conda-forge-admin, please rerender

**Comment by Anthchirp** [comment]
This time it worked! Suggest 

1. discussing/merging #8 first, then
2. merging master into here,
3. bumping the build number here,
4. merging this PR

**Comment by xmnlab** [comment]
@Anthchirp thanks for working on that. if you want to add yourself in this PR, that would be awesome .. as I am not using this package currently .. you have more usecases and idea about this package than me :)

If you don't want, no worries, just let me know and I will merge the PR :)

**Comment by Anthchirp** [comment]
Sure. Added myself as maintainer.

**Comment by xmnlab** [comment]
Thanks @Anthchirp!

**Pull request merged**
