### PR TITLE
Use latest version of HDF5

### PR DESCRIPTION
**Pull request by andersharrisson-ess**
This removes the explicit pinning of HDF (<1.9). To solve the test
failures this introduce (due to the newer version of h5py), the
test is patched. The patch is based on the following source commit:
https://github.com/kiyo-masui/bitshuffle/commit/81bcb6c87ac9fb46f77fcb19216568311bef16df

Resolves: #4

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by andersharrisson-ess** [comment]
@conda-forge-admin, please rerender

**Comment by ivan-usov** [comment]
@cpcloud, @xmnlab
Hi guys, this is a friendly reminder about this PR. It would be really great to have conda-forge bitshuffle package to be installed alongside with more recent h5py(>2.8) and hdf5/1.10 libs. Thanks a lot for your work.

**Comment by xmnlab** [comment]
thanks @andersharrisson-ess for working on this PR!
thanks @ivan-usov for ping me here. for some reason I missed the notification.

**Comment by andersharrisson-ess** [comment]
@xmnlab, thank you for the merge.

**Pull request merged**
